"""Add reimbursement_id to Expenditure model

Revision ID: e8cfcee229e6
Revises: 
Create Date: 2025-11-30 20:17:24.175103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cfcee229e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenditure', sa.Column('reimbursement_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'expenditure', type_='foreignkey')
    op.create_foreign_key(None, 'expenditure', 'reimbursement_request', ['reimbursement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenditure', type_='foreignkey')
    op.create_foreign_key(None, 'expenditure', 'design_team', ['design_team_id'], ['id'])
    op.drop_column('expenditure', 'reimbursement_id')
    # ### end Alembic commands ###
